// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: asr.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ASRRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*ASRRequest_Config
	//	*ASRRequest_Audio
	Request       isASRRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ASRRequest) Reset() {
	*x = ASRRequest{}
	mi := &file_asr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ASRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASRRequest) ProtoMessage() {}

func (x *ASRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASRRequest.ProtoReflect.Descriptor instead.
func (*ASRRequest) Descriptor() ([]byte, []int) {
	return file_asr_proto_rawDescGZIP(), []int{0}
}

func (x *ASRRequest) GetRequest() isASRRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ASRRequest) GetConfig() *StreamingConfig {
	if x != nil {
		if x, ok := x.Request.(*ASRRequest_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *ASRRequest) GetAudio() *AudioChunk {
	if x != nil {
		if x, ok := x.Request.(*ASRRequest_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

type isASRRequest_Request interface {
	isASRRequest_Request()
}

type ASRRequest_Config struct {
	Config *StreamingConfig `protobuf:"bytes,1,opt,name=config,proto3,oneof"`
}

type ASRRequest_Audio struct {
	Audio *AudioChunk `protobuf:"bytes,2,opt,name=audio,proto3,oneof"`
}

func (*ASRRequest_Config) isASRRequest_Request() {}

func (*ASRRequest_Audio) isASRRequest_Request() {}

type StreamingConfig struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Session                    *SessionInfo           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	EnableAutomaticPunctuation bool                   `protobuf:"varint,2,opt,name=enable_automatic_punctuation,json=enableAutomaticPunctuation,proto3" json:"enable_automatic_punctuation,omitempty"`
	EnableLanguageDetection    bool                   `protobuf:"varint,3,opt,name=enable_language_detection,json=enableLanguageDetection,proto3" json:"enable_language_detection,omitempty"`
	LanguageCodes              []string               `protobuf:"bytes,4,rep,name=language_codes,json=languageCodes,proto3" json:"language_codes,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *StreamingConfig) Reset() {
	*x = StreamingConfig{}
	mi := &file_asr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingConfig) ProtoMessage() {}

func (x *StreamingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_asr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingConfig.ProtoReflect.Descriptor instead.
func (*StreamingConfig) Descriptor() ([]byte, []int) {
	return file_asr_proto_rawDescGZIP(), []int{1}
}

func (x *StreamingConfig) GetSession() *SessionInfo {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *StreamingConfig) GetEnableAutomaticPunctuation() bool {
	if x != nil {
		return x.EnableAutomaticPunctuation
	}
	return false
}

func (x *StreamingConfig) GetEnableLanguageDetection() bool {
	if x != nil {
		return x.EnableLanguageDetection
	}
	return false
}

func (x *StreamingConfig) GetLanguageCodes() []string {
	if x != nil {
		return x.LanguageCodes
	}
	return nil
}

type ASRResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Transcript       string                 `protobuf:"bytes,2,opt,name=transcript,proto3" json:"transcript,omitempty"`
	IsFinal          bool                   `protobuf:"varint,3,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	Stability        float32                `protobuf:"fixed32,4,opt,name=stability,proto3" json:"stability,omitempty"`
	DetectedLanguage string                 `protobuf:"bytes,5,opt,name=detected_language,json=detectedLanguage,proto3" json:"detected_language,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ASRResponse) Reset() {
	*x = ASRResponse{}
	mi := &file_asr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ASRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASRResponse) ProtoMessage() {}

func (x *ASRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASRResponse.ProtoReflect.Descriptor instead.
func (*ASRResponse) Descriptor() ([]byte, []int) {
	return file_asr_proto_rawDescGZIP(), []int{2}
}

func (x *ASRResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ASRResponse) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

func (x *ASRResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *ASRResponse) GetStability() float32 {
	if x != nil {
		return x.Stability
	}
	return 0
}

func (x *ASRResponse) GetDetectedLanguage() string {
	if x != nil {
		return x.DetectedLanguage
	}
	return ""
}

var File_asr_proto protoreflect.FileDescriptor

const file_asr_proto_rawDesc = "" +
	"\n" +
	"\tasr.proto\x12\tapi.proto\x1a\fcommon.proto\"|\n" +
	"\n" +
	"ASRRequest\x124\n" +
	"\x06config\x18\x01 \x01(\v2\x1a.api.proto.StreamingConfigH\x00R\x06config\x12-\n" +
	"\x05audio\x18\x02 \x01(\v2\x15.api.proto.AudioChunkH\x00R\x05audioB\t\n" +
	"\arequest\"\xe8\x01\n" +
	"\x0fStreamingConfig\x120\n" +
	"\asession\x18\x01 \x01(\v2\x16.api.proto.SessionInfoR\asession\x12@\n" +
	"\x1cenable_automatic_punctuation\x18\x02 \x01(\bR\x1aenableAutomaticPunctuation\x12:\n" +
	"\x19enable_language_detection\x18\x03 \x01(\bR\x17enableLanguageDetection\x12%\n" +
	"\x0elanguage_codes\x18\x04 \x03(\tR\rlanguageCodes\"\xb2\x01\n" +
	"\vASRResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1e\n" +
	"\n" +
	"transcript\x18\x02 \x01(\tR\n" +
	"transcript\x12\x19\n" +
	"\bis_final\x18\x03 \x01(\bR\aisFinal\x12\x1c\n" +
	"\tstability\x18\x04 \x01(\x02R\tstability\x12+\n" +
	"\x11detected_language\x18\x05 \x01(\tR\x10detectedLanguage2U\n" +
	"\n" +
	"ASRService\x12G\n" +
	"\x12StreamingRecognize\x12\x15.api.proto.ASRRequest\x1a\x16.api.proto.ASRResponse(\x010\x01B\x1fZ\x1dai-translator/api/proto;protob\x06proto3"

var (
	file_asr_proto_rawDescOnce sync.Once
	file_asr_proto_rawDescData []byte
)

func file_asr_proto_rawDescGZIP() []byte {
	file_asr_proto_rawDescOnce.Do(func() {
		file_asr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_asr_proto_rawDesc), len(file_asr_proto_rawDesc)))
	})
	return file_asr_proto_rawDescData
}

var file_asr_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_asr_proto_goTypes = []any{
	(*ASRRequest)(nil),      // 0: api.proto.ASRRequest
	(*StreamingConfig)(nil), // 1: api.proto.StreamingConfig
	(*ASRResponse)(nil),     // 2: api.proto.ASRResponse
	(*AudioChunk)(nil),      // 3: api.proto.AudioChunk
	(*SessionInfo)(nil),     // 4: api.proto.SessionInfo
}
var file_asr_proto_depIdxs = []int32{
	1, // 0: api.proto.ASRRequest.config:type_name -> api.proto.StreamingConfig
	3, // 1: api.proto.ASRRequest.audio:type_name -> api.proto.AudioChunk
	4, // 2: api.proto.StreamingConfig.session:type_name -> api.proto.SessionInfo
	0, // 3: api.proto.ASRService.StreamingRecognize:input_type -> api.proto.ASRRequest
	2, // 4: api.proto.ASRService.StreamingRecognize:output_type -> api.proto.ASRResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_asr_proto_init() }
func file_asr_proto_init() {
	if File_asr_proto != nil {
		return
	}
	file_common_proto_init()
	file_asr_proto_msgTypes[0].OneofWrappers = []any{
		(*ASRRequest_Config)(nil),
		(*ASRRequest_Audio)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_asr_proto_rawDesc), len(file_asr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_asr_proto_goTypes,
		DependencyIndexes: file_asr_proto_depIdxs,
		MessageInfos:      file_asr_proto_msgTypes,
	}.Build()
	File_asr_proto = out.File
	file_asr_proto_goTypes = nil
	file_asr_proto_depIdxs = nil
}
