// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: translate.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TranslatorService_Translate_FullMethodName       = "/api.proto.TranslatorService/Translate"
	TranslatorService_StreamTranslate_FullMethodName = "/api.proto.TranslatorService/StreamTranslate"
)

// TranslatorServiceClient is the client API for TranslatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TranslatorServiceClient interface {
	Translate(ctx context.Context, in *TranslateRequest, opts ...grpc.CallOption) (*TranslateResponse, error)
	StreamTranslate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TranslateRequest, TranslateResponse], error)
}

type translatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTranslatorServiceClient(cc grpc.ClientConnInterface) TranslatorServiceClient {
	return &translatorServiceClient{cc}
}

func (c *translatorServiceClient) Translate(ctx context.Context, in *TranslateRequest, opts ...grpc.CallOption) (*TranslateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranslateResponse)
	err := c.cc.Invoke(ctx, TranslatorService_Translate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translatorServiceClient) StreamTranslate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TranslateRequest, TranslateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TranslatorService_ServiceDesc.Streams[0], TranslatorService_StreamTranslate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TranslateRequest, TranslateResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TranslatorService_StreamTranslateClient = grpc.BidiStreamingClient[TranslateRequest, TranslateResponse]

// TranslatorServiceServer is the server API for TranslatorService service.
// All implementations must embed UnimplementedTranslatorServiceServer
// for forward compatibility.
type TranslatorServiceServer interface {
	Translate(context.Context, *TranslateRequest) (*TranslateResponse, error)
	StreamTranslate(grpc.BidiStreamingServer[TranslateRequest, TranslateResponse]) error
	mustEmbedUnimplementedTranslatorServiceServer()
}

// UnimplementedTranslatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTranslatorServiceServer struct{}

func (UnimplementedTranslatorServiceServer) Translate(context.Context, *TranslateRequest) (*TranslateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Translate not implemented")
}
func (UnimplementedTranslatorServiceServer) StreamTranslate(grpc.BidiStreamingServer[TranslateRequest, TranslateResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamTranslate not implemented")
}
func (UnimplementedTranslatorServiceServer) mustEmbedUnimplementedTranslatorServiceServer() {}
func (UnimplementedTranslatorServiceServer) testEmbeddedByValue()                           {}

// UnsafeTranslatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranslatorServiceServer will
// result in compilation errors.
type UnsafeTranslatorServiceServer interface {
	mustEmbedUnimplementedTranslatorServiceServer()
}

func RegisterTranslatorServiceServer(s grpc.ServiceRegistrar, srv TranslatorServiceServer) {
	// If the following call panics, it indicates UnimplementedTranslatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TranslatorService_ServiceDesc, srv)
}

func _TranslatorService_Translate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranslateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslatorServiceServer).Translate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranslatorService_Translate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslatorServiceServer).Translate(ctx, req.(*TranslateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranslatorService_StreamTranslate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TranslatorServiceServer).StreamTranslate(&grpc.GenericServerStream[TranslateRequest, TranslateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TranslatorService_StreamTranslateServer = grpc.BidiStreamingServer[TranslateRequest, TranslateResponse]

// TranslatorService_ServiceDesc is the grpc.ServiceDesc for TranslatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TranslatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.proto.TranslatorService",
	HandlerType: (*TranslatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Translate",
			Handler:    _TranslatorService_Translate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTranslate",
			Handler:       _TranslatorService_StreamTranslate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "translate.proto",
}
