// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: tts.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TTSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	LanguageCode  string                 `protobuf:"bytes,3,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	VoiceConfig   *VoiceConfig           `protobuf:"bytes,4,opt,name=voice_config,json=voiceConfig,proto3" json:"voice_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TTSRequest) Reset() {
	*x = TTSRequest{}
	mi := &file_tts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TTSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTSRequest) ProtoMessage() {}

func (x *TTSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTSRequest.ProtoReflect.Descriptor instead.
func (*TTSRequest) Descriptor() ([]byte, []int) {
	return file_tts_proto_rawDescGZIP(), []int{0}
}

func (x *TTSRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TTSRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TTSRequest) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *TTSRequest) GetVoiceConfig() *VoiceConfig {
	if x != nil {
		return x.VoiceConfig
	}
	return nil
}

type VoiceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoiceName     string                 `protobuf:"bytes,1,opt,name=voice_name,json=voiceName,proto3" json:"voice_name,omitempty"`
	SpeakingRate  float32                `protobuf:"fixed32,2,opt,name=speaking_rate,json=speakingRate,proto3" json:"speaking_rate,omitempty"`
	Pitch         float32                `protobuf:"fixed32,3,opt,name=pitch,proto3" json:"pitch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceConfig) Reset() {
	*x = VoiceConfig{}
	mi := &file_tts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceConfig) ProtoMessage() {}

func (x *VoiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_tts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceConfig.ProtoReflect.Descriptor instead.
func (*VoiceConfig) Descriptor() ([]byte, []int) {
	return file_tts_proto_rawDescGZIP(), []int{1}
}

func (x *VoiceConfig) GetVoiceName() string {
	if x != nil {
		return x.VoiceName
	}
	return ""
}

func (x *VoiceConfig) GetSpeakingRate() float32 {
	if x != nil {
		return x.SpeakingRate
	}
	return 0
}

func (x *VoiceConfig) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

type TTSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Audio         *AudioChunk            `protobuf:"bytes,2,opt,name=audio,proto3" json:"audio,omitempty"`
	IsFinal       bool                   `protobuf:"varint,3,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TTSResponse) Reset() {
	*x = TTSResponse{}
	mi := &file_tts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TTSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTSResponse) ProtoMessage() {}

func (x *TTSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTSResponse.ProtoReflect.Descriptor instead.
func (*TTSResponse) Descriptor() ([]byte, []int) {
	return file_tts_proto_rawDescGZIP(), []int{2}
}

func (x *TTSResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TTSResponse) GetAudio() *AudioChunk {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *TTSResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

var File_tts_proto protoreflect.FileDescriptor

const file_tts_proto_rawDesc = "" +
	"\n" +
	"\ttts.proto\x12\tapi.proto\x1a\fcommon.proto\"\x9f\x01\n" +
	"\n" +
	"TTSRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12#\n" +
	"\rlanguage_code\x18\x03 \x01(\tR\flanguageCode\x129\n" +
	"\fvoice_config\x18\x04 \x01(\v2\x16.api.proto.VoiceConfigR\vvoiceConfig\"g\n" +
	"\vVoiceConfig\x12\x1d\n" +
	"\n" +
	"voice_name\x18\x01 \x01(\tR\tvoiceName\x12#\n" +
	"\rspeaking_rate\x18\x02 \x01(\x02R\fspeakingRate\x12\x14\n" +
	"\x05pitch\x18\x03 \x01(\x02R\x05pitch\"t\n" +
	"\vTTSResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12+\n" +
	"\x05audio\x18\x02 \x01(\v2\x15.api.proto.AudioChunkR\x05audio\x12\x19\n" +
	"\bis_final\x18\x03 \x01(\bR\aisFinal2\x92\x01\n" +
	"\n" +
	"TTSService\x12=\n" +
	"\n" +
	"Synthesize\x12\x15.api.proto.TTSRequest\x1a\x16.api.proto.TTSResponse0\x01\x12E\n" +
	"\x10StreamSynthesize\x12\x15.api.proto.TTSRequest\x1a\x16.api.proto.TTSResponse(\x010\x01B\x1fZ\x1dai-translator/api/proto;protob\x06proto3"

var (
	file_tts_proto_rawDescOnce sync.Once
	file_tts_proto_rawDescData []byte
)

func file_tts_proto_rawDescGZIP() []byte {
	file_tts_proto_rawDescOnce.Do(func() {
		file_tts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tts_proto_rawDesc), len(file_tts_proto_rawDesc)))
	})
	return file_tts_proto_rawDescData
}

var file_tts_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tts_proto_goTypes = []any{
	(*TTSRequest)(nil),  // 0: api.proto.TTSRequest
	(*VoiceConfig)(nil), // 1: api.proto.VoiceConfig
	(*TTSResponse)(nil), // 2: api.proto.TTSResponse
	(*AudioChunk)(nil),  // 3: api.proto.AudioChunk
}
var file_tts_proto_depIdxs = []int32{
	1, // 0: api.proto.TTSRequest.voice_config:type_name -> api.proto.VoiceConfig
	3, // 1: api.proto.TTSResponse.audio:type_name -> api.proto.AudioChunk
	0, // 2: api.proto.TTSService.Synthesize:input_type -> api.proto.TTSRequest
	0, // 3: api.proto.TTSService.StreamSynthesize:input_type -> api.proto.TTSRequest
	2, // 4: api.proto.TTSService.Synthesize:output_type -> api.proto.TTSResponse
	2, // 5: api.proto.TTSService.StreamSynthesize:output_type -> api.proto.TTSResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tts_proto_init() }
func file_tts_proto_init() {
	if File_tts_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tts_proto_rawDesc), len(file_tts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tts_proto_goTypes,
		DependencyIndexes: file_tts_proto_depIdxs,
		MessageInfos:      file_tts_proto_msgTypes,
	}.Build()
	File_tts_proto = out.File
	file_tts_proto_goTypes = nil
	file_tts_proto_depIdxs = nil
}
