// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: tts.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TTSService_Synthesize_FullMethodName       = "/api.proto.TTSService/Synthesize"
	TTSService_StreamSynthesize_FullMethodName = "/api.proto.TTSService/StreamSynthesize"
)

// TTSServiceClient is the client API for TTSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TTSServiceClient interface {
	Synthesize(ctx context.Context, in *TTSRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TTSResponse], error)
	StreamSynthesize(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TTSRequest, TTSResponse], error)
}

type tTSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTTSServiceClient(cc grpc.ClientConnInterface) TTSServiceClient {
	return &tTSServiceClient{cc}
}

func (c *tTSServiceClient) Synthesize(ctx context.Context, in *TTSRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TTSResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TTSService_ServiceDesc.Streams[0], TTSService_Synthesize_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TTSRequest, TTSResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTSService_SynthesizeClient = grpc.ServerStreamingClient[TTSResponse]

func (c *tTSServiceClient) StreamSynthesize(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TTSRequest, TTSResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TTSService_ServiceDesc.Streams[1], TTSService_StreamSynthesize_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TTSRequest, TTSResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTSService_StreamSynthesizeClient = grpc.BidiStreamingClient[TTSRequest, TTSResponse]

// TTSServiceServer is the server API for TTSService service.
// All implementations must embed UnimplementedTTSServiceServer
// for forward compatibility.
type TTSServiceServer interface {
	Synthesize(*TTSRequest, grpc.ServerStreamingServer[TTSResponse]) error
	StreamSynthesize(grpc.BidiStreamingServer[TTSRequest, TTSResponse]) error
	mustEmbedUnimplementedTTSServiceServer()
}

// UnimplementedTTSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTTSServiceServer struct{}

func (UnimplementedTTSServiceServer) Synthesize(*TTSRequest, grpc.ServerStreamingServer[TTSResponse]) error {
	return status.Error(codes.Unimplemented, "method Synthesize not implemented")
}
func (UnimplementedTTSServiceServer) StreamSynthesize(grpc.BidiStreamingServer[TTSRequest, TTSResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamSynthesize not implemented")
}
func (UnimplementedTTSServiceServer) mustEmbedUnimplementedTTSServiceServer() {}
func (UnimplementedTTSServiceServer) testEmbeddedByValue()                    {}

// UnsafeTTSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TTSServiceServer will
// result in compilation errors.
type UnsafeTTSServiceServer interface {
	mustEmbedUnimplementedTTSServiceServer()
}

func RegisterTTSServiceServer(s grpc.ServiceRegistrar, srv TTSServiceServer) {
	// If the following call panics, it indicates UnimplementedTTSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TTSService_ServiceDesc, srv)
}

func _TTSService_Synthesize_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TTSRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TTSServiceServer).Synthesize(m, &grpc.GenericServerStream[TTSRequest, TTSResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTSService_SynthesizeServer = grpc.ServerStreamingServer[TTSResponse]

func _TTSService_StreamSynthesize_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TTSServiceServer).StreamSynthesize(&grpc.GenericServerStream[TTSRequest, TTSResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTSService_StreamSynthesizeServer = grpc.BidiStreamingServer[TTSRequest, TTSResponse]

// TTSService_ServiceDesc is the grpc.ServiceDesc for TTSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TTSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.proto.TTSService",
	HandlerType: (*TTSServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Synthesize",
			Handler:       _TTSService_Synthesize_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamSynthesize",
			Handler:       _TTSService_StreamSynthesize_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "tts.proto",
}
